title: Cameron Marsh Artwork
url: 
baseurl: 

author: Cameron Marsh

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  etching:
    output: 
  lanscape:
    output: true
  figure:
    output: true 

markdown: kramdown
kramdown:
  input: GFM
